Merge pull request feat: #11, add Neo4j & MediatR integration
crowdparlay/social pull request #12
Opened 2023-05-13 19:34 UTC by zendet

#11

2023-05-14 14:28 UTC, undrcrxwn requested changes

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Queries/GetAuthorByIdQuery.cs
> +                })
Код-стайл
```cs
.WithParams(new
{
    Id = request.GetAuthorByIdDto.Id.ToString()
})
```

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Commands/DeleteAuthorCommand.cs
> +            .Delete("a").ExecuteWithoutResultsAsync();
Код-стайл
```cs
.Delete("a")
.ExecuteWithoutResultsAsync();
```

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Commands/CreateAuthorCommand.cs
> +                                    Alias: $Alias})")
Код-стайл. Как насчёт чего-то вроде
```cs
.Create(
    @"(a:Author {
        Id: $Id, 
        DisplayName: $DisplayName,
        AvatarUrl: $AvatarUrl,
        Alias: $Alias
    })")
```

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostController.cs
> +    }
`ActionResult` не используется, можно возвращать непосредственно саму дто: `Task<дто>` и `return await _mediator.Send(...);`

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostController.cs
> +        return CreatedAtAction(nameof(Get), new { createdPost });
Полезная нагрузка `CreatedAtAction` должна описывать путь к RESTful GET для созданной сущности. `new { createdPost }` здесь не подходит. Нужно заменить на `new { PostId = createdPost.Id }` и соответствующим образом отредактировать обработчик `Get`, чтобы он принимал это значение `createdPost.Id` не из query string (`GET /api/post/?id=123`) а из пути (route) (`GET /api/post/123`) по route-паттерну `{postId}`.

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostController.cs
> +    public async Task<ActionResult> Get([FromQuery] GetPostByIdDto getPostByIdDto)
`[FromQuery]` здесь неуместен. Заменить на `[FromRoute] Guid postId` в комбинации с `[HttpGet("{animalId}")]`.

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Queries/GetPostByIdQuery.cs
> +        var collection = result.Single();
Нет, точно не `collection`

2023-05-14 14:28 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/AuthorController.cs
> +public class AuthorController : ControllerBase
RESTful ресурсы принято называть в множественном числе. Соответственно, не `AuthorController`, а `AuthorsController`, не `GET /api/post/123`, а `GET /api/posts/123`.

2023-05-15 14:39 UTC, zendet commented on src/CrowdParlay.Social.Application/DTOs/Post/PostDto.cs
> +public class PostDto
Потому что у Neo4jClient наблюдаются проблемы с взаимодействием с "чистым" record'ом

2023-05-21 17:54 UTC, undrcrxwn requested changes

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/AuthorsController.cs
> +    public async Task<Unit> Delete([FromRoute] Guid authorId) =>
Зачем возвращать `Task<Unit>`? Возвращай просто `Task`.

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostsController.cs
> +[ApiController, Route("api/[controller]/[action]")]
`/[action]` здесь лишнее

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostsController.cs
> +    public async Task<ActionResult> Get([FromRoute] Guid postId)
`ActionResult` здесь бесполезен

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostsController.cs
> +    public async Task<ActionResult<IEnumerable<PostDto>>> GetAll(int offset, int limit)
`ActionResult` здесь бесполезен

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostsController.cs
> +    [HttpGet("{offset:int}/{limit:int}")]
`offset` и `limit` должны быть параметрами query string, а не сегментами route

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostsController.cs
> +    public async Task<CreatedAtActionResult> Create([FromRoute] Guid authorId, [FromBody] string content)
Почему на вход не дто?

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/DTOs/Author/AuthorDto.cs
> +}
Зачем так многословно? Рекорд на то и рекорд чтоб кратко модели описывать

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Commands/CreatePostCommand.cs
> +                request.Content,
Лишняя запятая в конце перечисления

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Commands/DeleteAuthorCommand.cs
> +public record DeleteAuthorCommand(Guid Id) : IRequest<Unit>;
Не `IRequest<Unit>`, а просто `IRequest`

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/ServiceCollectionExtensions.cs
> +        services.AddMediatR(Assembly.GetExecutingAssembly());
Переусложнено, объединить в один единый `AddApplication`

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Infrastructure/ServiceCollectionExtensions.cs
> +        var uri = configuration["NEO4J_URI"] ?? throw new InvalidOperationException("NEO4J_URI is not set!");
Код-стайл: перенос строки

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Infrastructure/ServiceCollectionExtensions.cs
> +                        throw new InvalidOperationException("NEO4J_PASSWORD is not set!");
Код-стайл
![image](https://github.com/crowdparlay/social/assets/69521267/6eb7df19-db1f-4049-a190-a2f0a4acff6e)

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Infrastructure/ServiceCollectionExtensions.cs
> +                        throw new InvalidOperationException("NEO4J_PASSWORD is not set!");
Как насчёт замены

```cs
a = b ??
    c;
```
на

```cs
a = b
    ?? c;
```

и выравнивание `c` будет всегда и везде одноуровневое, а не зависящее от положения `b`

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Infrastructure/ServiceCollectionExtensions.cs
> +
Код-стайл: два отступа подряд

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Infrastructure/Services/GraphClientInitialisator.cs
> +        await _graphClient.ConnectAsync();
Код-стайл: везде кроме этого участка кода однострочные тела методов заключаются в `{ ... }`, и только здесь предпочтение было отдано `=>`

2023-05-21 17:54 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/AuthorsController.cs
> +[ApiController, Route("api/[controller]/[action]/{authorId:guid}")]
`/[action]/{authorId:guid}` здесь лишнее

2023-05-23 08:27 UTC, undrcrxwn requested changes

2023-05-23 08:27 UTC, undrcrxwn commented on src/CrowdParlay.Social.Api/Controllers/PostsController.cs
> +    public async Task Get([FromRoute] Guid postId) =>
Почему `GET` ничего не возвращает? Наверное тут нужен `Task<дтошка>`

2023-05-23 08:27 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Commands/CreatePostCommand.cs
Названия файла совпадает с названием типа который описывается в этом файле только когда внутри файла лежит только один тип, так что в данном случае `CreatePostCommand.cs` не сильно отражает суть происходящего (в файле ведь не только `CreatePostCommand` лежит, но и хендлер + потенциально валидатор может добавиться или ещё что-нибудь), предлагаю переименовать в `CreatePost.cs`

2023-05-23 08:27 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Commands/CreatePostCommand.cs
С остальными файлами то же самое

2023-05-23 08:27 UTC, undrcrxwn commented on src/CrowdParlay.Social.Infrastructure/ServiceCollectionExtensions.cs
> +                       throw new InvalidOperationException("NEO4J_PASSWORD is not set!");
Код-стайл: просто рекомендация

![image](https://github.com/crowdparlay/social/assets/69521267/9ae4fbdf-4688-4eb6-857f-9f38f192f30e)

2023-05-23 08:27 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/DTOs/Author/AuthorDto.cs
> +    [Required] public string AvatarUrl { get; set; } = default!;
Рассмотри вариант замены DataAnnotations на `required` keyword из C# 11, если это возможно

2023-05-23 08:27 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/DTOs/Post/PostDto.cs
> +    [Required] public string Content { get; set; } = default!;
Пробел в конце строки. Расстрел.

2023-05-23 08:27 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/DTOs/Post/PostDto.cs
>      public AuthorDto AuthorDto { get; set; } = default!;
Если есть возможность использовать `required`, то лучше его использовать вместо того чтобы в не-nullable поле писать `null!`

2023-05-23 16:12 UTC, undrcrxwn requested changes

2023-05-23 16:12 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/DTOs/Author/AuthorDto.cs
> +    public required string AvatarUrl { get; set; } = default!;
` = default!;` здесь лишнее, `required` часто как раз и используется чтобы избежать инициализации `null!`

2023-05-23 16:12 UTC, undrcrxwn commented on src/CrowdParlay.Social.Application/Features/Commands/CreateAuthor.cs
> +public record CreateAuthor(Guid Id, string DisplayName, string AvatarUrl, string? Alias) : IRequest<AuthorDto>;
Верни типу прежнее название `CreateAuthorCommand`, и с остальными так же

2023-05-23 16:12 UTC, undrcrxwn commented on src/CrowdParlay.Social.Infrastructure/ServiceCollectionExtensions.cs
> +           throw new InvalidOperationException("NEO4J_PASSWORD is not set!");
Код-стайл

![image](https://github.com/crowdparlay/social/assets/69521267/37f165bd-9629-4353-8e9b-0bbccf8a5de6)

2023-05-24 07:16 UTC, merged